name: Semantic Versioning and Publish to NPM

on:
  push:
    branches:
      - master
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ“š Checkout
        uses: actions/checkout@v2
      - name: ğŸŸ¢ Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: â˜ Install dependencies
        run: yarn
      - name: ğŸš¦ Semantic Versioning
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: npx semantic-release

  publish-npm:
    needs: publish
    runs-on: ubuntu-latest
    steps:
      - name: â¬‡ Git Pull
        run: git pull origin master
      - name: ğŸ“š Checkout
        uses: actions/checkout@v3
      - name: ğŸŸ¢ Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - name: ğŸš€ Publish NPM
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
